name: Flask CI

on:
  push:
    branches: [ "new_feature/unit_tests" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: TelemetrySite/server

      - name: Run tests
        run: pytest tests/
        working-directory: TelemetrySite/server